// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_s2c.proto

#ifndef PROTOBUF_msg_5fs2c_2eproto__INCLUDED
#define PROTOBUF_msg_5fs2c_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "define_pro.pb.h"
#include "define_attrib.pb.h"
#include "msg_player.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fs2c_2eproto();
void protobuf_AssignDesc_msg_5fs2c_2eproto();
void protobuf_ShutdownFile_msg_5fs2c_2eproto();

class MsgSetSession;
class MsgSyncDataCheckSum;

// ===================================================================

class MsgSetSession : public ::google::protobuf::Message {
 public:
  MsgSetSession();
  virtual ~MsgSetSession();

  MsgSetSession(const MsgSetSession& from);

  inline MsgSetSession& operator=(const MsgSetSession& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSetSession& default_instance();

  void Swap(MsgSetSession* other);

  // implements Message ----------------------------------------------

  MsgSetSession* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSetSession& from);
  void MergeFrom(const MsgSetSession& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 seed = 1;
  inline bool has_seed() const;
  inline void clear_seed();
  static const int kSeedFieldNumber = 1;
  inline ::google::protobuf::uint32 seed() const;
  inline void set_seed(::google::protobuf::uint32 value);

  // optional fixed64 session = 2;
  inline bool has_session() const;
  inline void clear_session();
  static const int kSessionFieldNumber = 2;
  inline ::google::protobuf::uint64 session() const;
  inline void set_session(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MsgSetSession)
 private:
  inline void set_has_seed();
  inline void clear_has_seed();
  inline void set_has_session();
  inline void clear_has_session();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 session_;
  ::google::protobuf::uint32 seed_;
  friend void  protobuf_AddDesc_msg_5fs2c_2eproto();
  friend void protobuf_AssignDesc_msg_5fs2c_2eproto();
  friend void protobuf_ShutdownFile_msg_5fs2c_2eproto();

  void InitAsDefaultInstance();
  static MsgSetSession* default_instance_;
};
// -------------------------------------------------------------------

class MsgSyncDataCheckSum : public ::google::protobuf::Message {
 public:
  MsgSyncDataCheckSum();
  virtual ~MsgSyncDataCheckSum();

  MsgSyncDataCheckSum(const MsgSyncDataCheckSum& from);

  inline MsgSyncDataCheckSum& operator=(const MsgSyncDataCheckSum& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSyncDataCheckSum& default_instance();

  void Swap(MsgSyncDataCheckSum* other);

  // implements Message ----------------------------------------------

  MsgSyncDataCheckSum* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSyncDataCheckSum& from);
  void MergeFrom(const MsgSyncDataCheckSum& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 item_canuse = 1;
  inline bool has_item_canuse() const;
  inline void clear_item_canuse();
  static const int kItemCanuseFieldNumber = 1;
  inline ::google::protobuf::uint32 item_canuse() const;
  inline void set_item_canuse(::google::protobuf::uint32 value);

  // optional fixed32 item_stuff = 2;
  inline bool has_item_stuff() const;
  inline void clear_item_stuff();
  static const int kItemStuffFieldNumber = 2;
  inline ::google::protobuf::uint32 item_stuff() const;
  inline void set_item_stuff(::google::protobuf::uint32 value);

  // optional fixed32 item_guard_card = 3;
  inline bool has_item_guard_card() const;
  inline void clear_item_guard_card();
  static const int kItemGuardCardFieldNumber = 3;
  inline ::google::protobuf::uint32 item_guard_card() const;
  inline void set_item_guard_card(::google::protobuf::uint32 value);

  // optional fixed32 item_use_limit = 4;
  inline bool has_item_use_limit() const;
  inline void clear_item_use_limit();
  static const int kItemUseLimitFieldNumber = 4;
  inline ::google::protobuf::uint32 item_use_limit() const;
  inline void set_item_use_limit(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgSyncDataCheckSum)
 private:
  inline void set_has_item_canuse();
  inline void clear_has_item_canuse();
  inline void set_has_item_stuff();
  inline void clear_has_item_stuff();
  inline void set_has_item_guard_card();
  inline void clear_has_item_guard_card();
  inline void set_has_item_use_limit();
  inline void clear_has_item_use_limit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 item_canuse_;
  ::google::protobuf::uint32 item_stuff_;
  ::google::protobuf::uint32 item_guard_card_;
  ::google::protobuf::uint32 item_use_limit_;
  friend void  protobuf_AddDesc_msg_5fs2c_2eproto();
  friend void protobuf_AssignDesc_msg_5fs2c_2eproto();
  friend void protobuf_ShutdownFile_msg_5fs2c_2eproto();

  void InitAsDefaultInstance();
  static MsgSyncDataCheckSum* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgSetSession

// optional fixed32 seed = 1;
inline bool MsgSetSession::has_seed() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSetSession::set_has_seed() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSetSession::clear_has_seed() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSetSession::clear_seed() {
  seed_ = 0u;
  clear_has_seed();
}
inline ::google::protobuf::uint32 MsgSetSession::seed() const {
  // @@protoc_insertion_point(field_get:MsgSetSession.seed)
  return seed_;
}
inline void MsgSetSession::set_seed(::google::protobuf::uint32 value) {
  set_has_seed();
  seed_ = value;
  // @@protoc_insertion_point(field_set:MsgSetSession.seed)
}

// optional fixed64 session = 2;
inline bool MsgSetSession::has_session() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgSetSession::set_has_session() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgSetSession::clear_has_session() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgSetSession::clear_session() {
  session_ = GOOGLE_ULONGLONG(0);
  clear_has_session();
}
inline ::google::protobuf::uint64 MsgSetSession::session() const {
  // @@protoc_insertion_point(field_get:MsgSetSession.session)
  return session_;
}
inline void MsgSetSession::set_session(::google::protobuf::uint64 value) {
  set_has_session();
  session_ = value;
  // @@protoc_insertion_point(field_set:MsgSetSession.session)
}

// -------------------------------------------------------------------

// MsgSyncDataCheckSum

// optional fixed32 item_canuse = 1;
inline bool MsgSyncDataCheckSum::has_item_canuse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSyncDataCheckSum::set_has_item_canuse() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSyncDataCheckSum::clear_has_item_canuse() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSyncDataCheckSum::clear_item_canuse() {
  item_canuse_ = 0u;
  clear_has_item_canuse();
}
inline ::google::protobuf::uint32 MsgSyncDataCheckSum::item_canuse() const {
  // @@protoc_insertion_point(field_get:MsgSyncDataCheckSum.item_canuse)
  return item_canuse_;
}
inline void MsgSyncDataCheckSum::set_item_canuse(::google::protobuf::uint32 value) {
  set_has_item_canuse();
  item_canuse_ = value;
  // @@protoc_insertion_point(field_set:MsgSyncDataCheckSum.item_canuse)
}

// optional fixed32 item_stuff = 2;
inline bool MsgSyncDataCheckSum::has_item_stuff() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgSyncDataCheckSum::set_has_item_stuff() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgSyncDataCheckSum::clear_has_item_stuff() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgSyncDataCheckSum::clear_item_stuff() {
  item_stuff_ = 0u;
  clear_has_item_stuff();
}
inline ::google::protobuf::uint32 MsgSyncDataCheckSum::item_stuff() const {
  // @@protoc_insertion_point(field_get:MsgSyncDataCheckSum.item_stuff)
  return item_stuff_;
}
inline void MsgSyncDataCheckSum::set_item_stuff(::google::protobuf::uint32 value) {
  set_has_item_stuff();
  item_stuff_ = value;
  // @@protoc_insertion_point(field_set:MsgSyncDataCheckSum.item_stuff)
}

// optional fixed32 item_guard_card = 3;
inline bool MsgSyncDataCheckSum::has_item_guard_card() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgSyncDataCheckSum::set_has_item_guard_card() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgSyncDataCheckSum::clear_has_item_guard_card() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgSyncDataCheckSum::clear_item_guard_card() {
  item_guard_card_ = 0u;
  clear_has_item_guard_card();
}
inline ::google::protobuf::uint32 MsgSyncDataCheckSum::item_guard_card() const {
  // @@protoc_insertion_point(field_get:MsgSyncDataCheckSum.item_guard_card)
  return item_guard_card_;
}
inline void MsgSyncDataCheckSum::set_item_guard_card(::google::protobuf::uint32 value) {
  set_has_item_guard_card();
  item_guard_card_ = value;
  // @@protoc_insertion_point(field_set:MsgSyncDataCheckSum.item_guard_card)
}

// optional fixed32 item_use_limit = 4;
inline bool MsgSyncDataCheckSum::has_item_use_limit() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgSyncDataCheckSum::set_has_item_use_limit() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgSyncDataCheckSum::clear_has_item_use_limit() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgSyncDataCheckSum::clear_item_use_limit() {
  item_use_limit_ = 0u;
  clear_has_item_use_limit();
}
inline ::google::protobuf::uint32 MsgSyncDataCheckSum::item_use_limit() const {
  // @@protoc_insertion_point(field_get:MsgSyncDataCheckSum.item_use_limit)
  return item_use_limit_;
}
inline void MsgSyncDataCheckSum::set_item_use_limit(::google::protobuf::uint32 value) {
  set_has_item_use_limit();
  item_use_limit_ = value;
  // @@protoc_insertion_point(field_set:MsgSyncDataCheckSum.item_use_limit)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fs2c_2eproto__INCLUDED
