// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define_sys.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "define_sys.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MsgDataHead_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgDataHead_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgSession_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgSession_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgPart_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgPart_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TUdpControlFlag_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* TUdpControlCmd_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_define_5fsys_2eproto() {
  protobuf_AddDesc_define_5fsys_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "define_sys.proto");
  GOOGLE_CHECK(file != NULL);
  MsgDataHead_descriptor_ = file->message_type(0);
  static const int MsgDataHead_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, control_flag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, control_cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, ack_idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, msg_idx_),
  };
  MsgDataHead_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgDataHead_descriptor_,
      MsgDataHead::default_instance_,
      MsgDataHead_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgDataHead, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgDataHead));
  MsgSession_descriptor_ = file->message_type(1);
  static const int MsgSession_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSession, session_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSession, check_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSession, index_),
  };
  MsgSession_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgSession_descriptor_,
      MsgSession::default_instance_,
      MsgSession_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSession, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSession, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgSession));
  MsgPart_descriptor_ = file->message_type(2);
  static const int MsgPart_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, msg_idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, part_idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, part_max_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, msg_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, msg_body_),
  };
  MsgPart_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgPart_descriptor_,
      MsgPart::default_instance_,
      MsgPart_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgPart, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgPart));
  TUdpControlFlag_descriptor_ = file->enum_type(0);
  TUdpControlCmd_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_define_5fsys_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgDataHead_descriptor_, &MsgDataHead::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgSession_descriptor_, &MsgSession::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgPart_descriptor_, &MsgPart::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_define_5fsys_2eproto() {
  delete MsgDataHead::default_instance_;
  delete MsgDataHead_reflection_;
  delete MsgSession::default_instance_;
  delete MsgSession_reflection_;
  delete MsgPart::default_instance_;
  delete MsgPart_reflection_;
}

void protobuf_AddDesc_define_5fsys_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020define_sys.proto\"Z\n\013MsgDataHead\022\024\n\014con"
    "trol_flag\030\001 \001(\r\022\023\n\013control_cmd\030\002 \001(\r\022\017\n\007"
    "ack_idx\030\003 \001(\r\022\017\n\007msg_idx\030\004 \001(\r\";\n\nMsgSes"
    "sion\022\017\n\007session\030\001 \001(\t\022\r\n\005check\030\002 \001(\007\022\r\n\005"
    "index\030\003 \001(\r\"b\n\007MsgPart\022\017\n\007msg_idx\030\001 \001(\r\022"
    "\020\n\010part_idx\030\002 \001(\r\022\020\n\010part_max\030\003 \001(\r\022\020\n\010m"
    "sg_name\030\004 \001(\t\022\020\n\010msg_body\030\005 \001(\014*5\n\017TUdpC"
    "ontrolFlag\022\r\n\tPROTO_CMD\020\001\022\023\n\016PROTO_NEED_"
    "ACK\020\200\001*<\n\016TUdpControlCmd\022\021\n\rPROTO_CMD_AC"
    "K\020\001\022\027\n\023PROTO_CMD_HEARTBEAT\020\002", 388);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "define_sys.proto", &protobuf_RegisterTypes);
  MsgDataHead::default_instance_ = new MsgDataHead();
  MsgSession::default_instance_ = new MsgSession();
  MsgPart::default_instance_ = new MsgPart();
  MsgDataHead::default_instance_->InitAsDefaultInstance();
  MsgSession::default_instance_->InitAsDefaultInstance();
  MsgPart::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_define_5fsys_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_define_5fsys_2eproto {
  StaticDescriptorInitializer_define_5fsys_2eproto() {
    protobuf_AddDesc_define_5fsys_2eproto();
  }
} static_descriptor_initializer_define_5fsys_2eproto_;
const ::google::protobuf::EnumDescriptor* TUdpControlFlag_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TUdpControlFlag_descriptor_;
}
bool TUdpControlFlag_IsValid(int value) {
  switch(value) {
    case 1:
    case 128:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* TUdpControlCmd_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TUdpControlCmd_descriptor_;
}
bool TUdpControlCmd_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int MsgDataHead::kControlFlagFieldNumber;
const int MsgDataHead::kControlCmdFieldNumber;
const int MsgDataHead::kAckIdxFieldNumber;
const int MsgDataHead::kMsgIdxFieldNumber;
#endif  // !_MSC_VER

MsgDataHead::MsgDataHead()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgDataHead)
}

void MsgDataHead::InitAsDefaultInstance() {
}

MsgDataHead::MsgDataHead(const MsgDataHead& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgDataHead)
}

void MsgDataHead::SharedCtor() {
  _cached_size_ = 0;
  control_flag_ = 0u;
  control_cmd_ = 0u;
  ack_idx_ = 0u;
  msg_idx_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgDataHead::~MsgDataHead() {
  // @@protoc_insertion_point(destructor:MsgDataHead)
  SharedDtor();
}

void MsgDataHead::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgDataHead::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgDataHead::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgDataHead_descriptor_;
}

const MsgDataHead& MsgDataHead::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_define_5fsys_2eproto();
  return *default_instance_;
}

MsgDataHead* MsgDataHead::default_instance_ = NULL;

MsgDataHead* MsgDataHead::New() const {
  return new MsgDataHead;
}

void MsgDataHead::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MsgDataHead*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(control_flag_, msg_idx_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgDataHead::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgDataHead)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 control_flag = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &control_flag_)));
          set_has_control_flag();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_control_cmd;
        break;
      }

      // optional uint32 control_cmd = 2;
      case 2: {
        if (tag == 16) {
         parse_control_cmd:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &control_cmd_)));
          set_has_control_cmd();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_ack_idx;
        break;
      }

      // optional uint32 ack_idx = 3;
      case 3: {
        if (tag == 24) {
         parse_ack_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ack_idx_)));
          set_has_ack_idx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_msg_idx;
        break;
      }

      // optional uint32 msg_idx = 4;
      case 4: {
        if (tag == 32) {
         parse_msg_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msg_idx_)));
          set_has_msg_idx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgDataHead)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgDataHead)
  return false;
#undef DO_
}

void MsgDataHead::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgDataHead)
  // optional uint32 control_flag = 1;
  if (has_control_flag()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->control_flag(), output);
  }

  // optional uint32 control_cmd = 2;
  if (has_control_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->control_cmd(), output);
  }

  // optional uint32 ack_idx = 3;
  if (has_ack_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->ack_idx(), output);
  }

  // optional uint32 msg_idx = 4;
  if (has_msg_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->msg_idx(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgDataHead)
}

::google::protobuf::uint8* MsgDataHead::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgDataHead)
  // optional uint32 control_flag = 1;
  if (has_control_flag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->control_flag(), target);
  }

  // optional uint32 control_cmd = 2;
  if (has_control_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->control_cmd(), target);
  }

  // optional uint32 ack_idx = 3;
  if (has_ack_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->ack_idx(), target);
  }

  // optional uint32 msg_idx = 4;
  if (has_msg_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->msg_idx(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgDataHead)
  return target;
}

int MsgDataHead::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 control_flag = 1;
    if (has_control_flag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->control_flag());
    }

    // optional uint32 control_cmd = 2;
    if (has_control_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->control_cmd());
    }

    // optional uint32 ack_idx = 3;
    if (has_ack_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->ack_idx());
    }

    // optional uint32 msg_idx = 4;
    if (has_msg_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->msg_idx());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgDataHead::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgDataHead* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgDataHead*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgDataHead::MergeFrom(const MsgDataHead& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_control_flag()) {
      set_control_flag(from.control_flag());
    }
    if (from.has_control_cmd()) {
      set_control_cmd(from.control_cmd());
    }
    if (from.has_ack_idx()) {
      set_ack_idx(from.ack_idx());
    }
    if (from.has_msg_idx()) {
      set_msg_idx(from.msg_idx());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgDataHead::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgDataHead::CopyFrom(const MsgDataHead& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgDataHead::IsInitialized() const {

  return true;
}

void MsgDataHead::Swap(MsgDataHead* other) {
  if (other != this) {
    std::swap(control_flag_, other->control_flag_);
    std::swap(control_cmd_, other->control_cmd_);
    std::swap(ack_idx_, other->ack_idx_);
    std::swap(msg_idx_, other->msg_idx_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgDataHead::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgDataHead_descriptor_;
  metadata.reflection = MsgDataHead_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgSession::kSessionFieldNumber;
const int MsgSession::kCheckFieldNumber;
const int MsgSession::kIndexFieldNumber;
#endif  // !_MSC_VER

MsgSession::MsgSession()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgSession)
}

void MsgSession::InitAsDefaultInstance() {
}

MsgSession::MsgSession(const MsgSession& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgSession)
}

void MsgSession::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  session_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  check_ = 0u;
  index_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgSession::~MsgSession() {
  // @@protoc_insertion_point(destructor:MsgSession)
  SharedDtor();
}

void MsgSession::SharedDtor() {
  if (session_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete session_;
  }
  if (this != default_instance_) {
  }
}

void MsgSession::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgSession::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgSession_descriptor_;
}

const MsgSession& MsgSession::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_define_5fsys_2eproto();
  return *default_instance_;
}

MsgSession* MsgSession::default_instance_ = NULL;

MsgSession* MsgSession::New() const {
  return new MsgSession;
}

void MsgSession::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MsgSession*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(check_, index_);
    if (has_session()) {
      if (session_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        session_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgSession::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgSession)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string session = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->session().data(), this->session().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "session");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_check;
        break;
      }

      // optional fixed32 check = 2;
      case 2: {
        if (tag == 21) {
         parse_check:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &check_)));
          set_has_check();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_index;
        break;
      }

      // optional uint32 index = 3;
      case 3: {
        if (tag == 24) {
         parse_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
          set_has_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgSession)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgSession)
  return false;
#undef DO_
}

void MsgSession::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgSession)
  // optional string session = 1;
  if (has_session()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session().data(), this->session().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->session(), output);
  }

  // optional fixed32 check = 2;
  if (has_check()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(2, this->check(), output);
  }

  // optional uint32 index = 3;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->index(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgSession)
}

::google::protobuf::uint8* MsgSession::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgSession)
  // optional string session = 1;
  if (has_session()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session().data(), this->session().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->session(), target);
  }

  // optional fixed32 check = 2;
  if (has_check()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(2, this->check(), target);
  }

  // optional uint32 index = 3;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->index(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgSession)
  return target;
}

int MsgSession::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string session = 1;
    if (has_session()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->session());
    }

    // optional fixed32 check = 2;
    if (has_check()) {
      total_size += 1 + 4;
    }

    // optional uint32 index = 3;
    if (has_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->index());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgSession::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgSession* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgSession*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgSession::MergeFrom(const MsgSession& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session()) {
      set_session(from.session());
    }
    if (from.has_check()) {
      set_check(from.check());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgSession::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgSession::CopyFrom(const MsgSession& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSession::IsInitialized() const {

  return true;
}

void MsgSession::Swap(MsgSession* other) {
  if (other != this) {
    std::swap(session_, other->session_);
    std::swap(check_, other->check_);
    std::swap(index_, other->index_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgSession::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgSession_descriptor_;
  metadata.reflection = MsgSession_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgPart::kMsgIdxFieldNumber;
const int MsgPart::kPartIdxFieldNumber;
const int MsgPart::kPartMaxFieldNumber;
const int MsgPart::kMsgNameFieldNumber;
const int MsgPart::kMsgBodyFieldNumber;
#endif  // !_MSC_VER

MsgPart::MsgPart()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgPart)
}

void MsgPart::InitAsDefaultInstance() {
}

MsgPart::MsgPart(const MsgPart& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgPart)
}

void MsgPart::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msg_idx_ = 0u;
  part_idx_ = 0u;
  part_max_ = 0u;
  msg_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgPart::~MsgPart() {
  // @@protoc_insertion_point(destructor:MsgPart)
  SharedDtor();
}

void MsgPart::SharedDtor() {
  if (msg_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_name_;
  }
  if (msg_body_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_body_;
  }
  if (this != default_instance_) {
  }
}

void MsgPart::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgPart::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgPart_descriptor_;
}

const MsgPart& MsgPart::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_define_5fsys_2eproto();
  return *default_instance_;
}

MsgPart* MsgPart::default_instance_ = NULL;

MsgPart* MsgPart::New() const {
  return new MsgPart;
}

void MsgPart::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MsgPart*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(msg_idx_, part_idx_);
    part_max_ = 0u;
    if (has_msg_name()) {
      if (msg_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        msg_name_->clear();
      }
    }
    if (has_msg_body()) {
      if (msg_body_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        msg_body_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgPart::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgPart)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 msg_idx = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msg_idx_)));
          set_has_msg_idx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_part_idx;
        break;
      }

      // optional uint32 part_idx = 2;
      case 2: {
        if (tag == 16) {
         parse_part_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &part_idx_)));
          set_has_part_idx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_part_max;
        break;
      }

      // optional uint32 part_max = 3;
      case 3: {
        if (tag == 24) {
         parse_part_max:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &part_max_)));
          set_has_part_max();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_msg_name;
        break;
      }

      // optional string msg_name = 4;
      case 4: {
        if (tag == 34) {
         parse_msg_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msg_name().data(), this->msg_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msg_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_msg_body;
        break;
      }

      // optional bytes msg_body = 5;
      case 5: {
        if (tag == 42) {
         parse_msg_body:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_msg_body()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgPart)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgPart)
  return false;
#undef DO_
}

void MsgPart::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgPart)
  // optional uint32 msg_idx = 1;
  if (has_msg_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->msg_idx(), output);
  }

  // optional uint32 part_idx = 2;
  if (has_part_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->part_idx(), output);
  }

  // optional uint32 part_max = 3;
  if (has_part_max()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->part_max(), output);
  }

  // optional string msg_name = 4;
  if (has_msg_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg_name().data(), this->msg_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->msg_name(), output);
  }

  // optional bytes msg_body = 5;
  if (has_msg_body()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->msg_body(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgPart)
}

::google::protobuf::uint8* MsgPart::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgPart)
  // optional uint32 msg_idx = 1;
  if (has_msg_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->msg_idx(), target);
  }

  // optional uint32 part_idx = 2;
  if (has_part_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->part_idx(), target);
  }

  // optional uint32 part_max = 3;
  if (has_part_max()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->part_max(), target);
  }

  // optional string msg_name = 4;
  if (has_msg_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg_name().data(), this->msg_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->msg_name(), target);
  }

  // optional bytes msg_body = 5;
  if (has_msg_body()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->msg_body(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgPart)
  return target;
}

int MsgPart::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 msg_idx = 1;
    if (has_msg_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->msg_idx());
    }

    // optional uint32 part_idx = 2;
    if (has_part_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->part_idx());
    }

    // optional uint32 part_max = 3;
    if (has_part_max()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->part_max());
    }

    // optional string msg_name = 4;
    if (has_msg_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg_name());
    }

    // optional bytes msg_body = 5;
    if (has_msg_body()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->msg_body());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgPart::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgPart* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgPart*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgPart::MergeFrom(const MsgPart& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg_idx()) {
      set_msg_idx(from.msg_idx());
    }
    if (from.has_part_idx()) {
      set_part_idx(from.part_idx());
    }
    if (from.has_part_max()) {
      set_part_max(from.part_max());
    }
    if (from.has_msg_name()) {
      set_msg_name(from.msg_name());
    }
    if (from.has_msg_body()) {
      set_msg_body(from.msg_body());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgPart::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgPart::CopyFrom(const MsgPart& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgPart::IsInitialized() const {

  return true;
}

void MsgPart::Swap(MsgPart* other) {
  if (other != this) {
    std::swap(msg_idx_, other->msg_idx_);
    std::swap(part_idx_, other->part_idx_);
    std::swap(part_max_, other->part_max_);
    std::swap(msg_name_, other->msg_name_);
    std::swap(msg_body_, other->msg_body_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgPart::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgPart_descriptor_;
  metadata.reflection = MsgPart_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
