// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define_attrib.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "define_attrib.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ATTRIB_TYPE {

namespace {

const ::google::protobuf::EnumDescriptor* TAttribType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_define_5fattrib_2eproto() {
  protobuf_AddDesc_define_5fattrib_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "define_attrib.proto");
  GOOGLE_CHECK(file != NULL);
  TAttribType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_define_5fattrib_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_define_5fattrib_2eproto() {
}

void protobuf_AddDesc_define_5fattrib_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023define_attrib.proto\022\013ATTRIB_TYPE*\216\001\n\013T"
    "AttribType\022\030\n\013INVALID_VAL\020\377\377\377\377\377\377\377\377\377\001\022\013\n\007"
    "INVALID\020\000\022\010\n\002ID\020\351\220z\022\026\n\020LEVEL_UP_EXP_INT\020"
    "\352\220z\022\021\n\013NAME_STRING\020\353\220z\022\016\n\010LIFE_INT\020\354\220z\022\023"
    "\n\rLIFE_CURR_INT\020\355\220z", 179);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "define_attrib.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_define_5fattrib_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_define_5fattrib_2eproto {
  StaticDescriptorInitializer_define_5fattrib_2eproto() {
    protobuf_AddDesc_define_5fattrib_2eproto();
  }
} static_descriptor_initializer_define_5fattrib_2eproto_;
const ::google::protobuf::EnumDescriptor* TAttribType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TAttribType_descriptor_;
}
bool TAttribType_IsValid(int value) {
  switch(value) {
    case -1:
    case 0:
    case 2001001:
    case 2001002:
    case 2001003:
    case 2001004:
    case 2001005:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ATTRIB_TYPE

// @@protoc_insertion_point(global_scope)
